##
## Makefile for  in /home/menich_a/rendu/cpp_bomberman
## 
## Made by Anatole Menichetti
## Login   <menich_a@epitech.net>
## 
## Started on  Sun Jun 14 18:00:53 2015 Anatole Menichetti
## Last update Sun Jun 14 18:03:33 2015 Anatole Menichetti
##

all:
	cd Game && make

clean:
	cd Game && make clean

fclean: clean
	rm Game/bomberman

re: 	fclean all

.PHONY:	all clean fclean re

